version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_evpiu
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/cert:/etc/nginx/ssl
    links:
      - app
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        XDEBUG: 1
        PHP_IDE_CONFIG: "serverName=evpiu.test"
    container_name: app_evpiu
    volumes:
      - ./:/var/www/html

      - type: volume
        source: Certificates
        target: /var/www/html/storage/app/certificates
        volume:
          nocopy: true

      - type: volume
        source: Qnap
        target: /var/www/html/storage/app
        volume:
          nocopy: true
    ports:
      - "5172:5172"

volumes:
  Certificates:
    driver: local
    driver_opts:
      device: ":APLICACIONES/APIDIAN/storage/app/certificates"
      o: "addr=192.168.1.49,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      type: nfs
  Qnap:
    driver: local
    driver_opts:
      device: ":APLICACIONES/EVPIU/storage/app"
      o: "addr=192.168.1.49,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4"
      type: nfs
